{% set name = "mage-ai" %}
{% set version = "0.8.46" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4a89ea62a17b0db1d0bf46e1d295f54ec19dcf167d21d14ea2f9b5f3e13a3011

build:
  noarch: python
  skip_compile_pyc:
    - '*/templates/*.py'          # These should not (and cannot) be compiled
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - mage = mage_ai.cli.main:app

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - Faker ==4.14.0
    - GitPython ==3.1.31
    - Jinja2 ~=3.0.3
    - PyJWT ==2.6.0
    - aiofiles ==22.1.0
    - alembic >=1.7.5
    - bcrypt
    - croniter ==1.3.7
    - cryptography ==36.0.2
    - dask >=2022.2.0
    - datadog ==0.44.0
    - freezegun ==1.2.2
    - inflection ==0.5.1
    - ipykernel ==6.15.0
    - ipython
    - itsdangerous ~=1.1.0
    - joblib >=1.1.0
    - jupyter_client ==7.3.4
    - jupyter-server-proxy ==3.2.1
    - numpy >=1.21.0
    - pandas >=1.3.0
    - protobuf
    - pyarrow ==10.0.1
    - python-dateutil ==2.8.2
    - pytz ==2022.1
    - pyyaml ~=6.0
    - requests ==2.27.1
    - scikit-learn >=1.0
    - simplejson
    - six >=1.15.0
    - sqlalchemy >=1.4.20, <2.0.0
    - terminado ==0.17.1
    - tornado ==6.1
    - typer ==0.7.0
  run_constrained:
    - great-expectations ==0.15.50
    - httpx ==0.23.1
    - jupyter_server ==1.23.5


test:
  commands:
    - python -m unittest discover
  imports:
    - mage_ai

about:
  home: https://github.com/mage-ai/mage-ai
  summary: Mage is an open-source tool for building and running data pipelines that transform your data.
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  doc_url: https://github.com/mage-ai/mage-ai/tree/master/docs
  dev_url: https://github.com/mage-ai/mage-ai

extra:
  recipe-maintainers:
    - wangxiaoyou1993
